update bash convenience

diff --git a/scripts/bash_convenience b/scripts/bash_convenience
--- a/scripts/bash_convenience
+++ b/scripts/bash_convenience
@@ -1,37 +1,95 @@
-
-alias k="kubectl"
-
 export KUBESPACE=malcolm
 
+command -v kubectl >/dev/null 2>&1 && alias k=kubectl
+
+function kctl () {
+  if [[ -n "${KUBECONFIG}" ]]; then
+    kubectl --kubeconfig "${KUBECONFIG}" "$@"
+  else
+    kubectl "$@"
+  fi
+}
+
+function kstern () {
+  if [[ -n "${KUBECONFIG}" ]]; then
+    stern --kubeconfig "${KUBECONFIG}" "$@"
+  else
+    stern "$@"
+  fi
+}
+
 function kpods () {
-    local NAMESPACE="${1:-$KUBESPACE}"
-    kubectl --kubeconfig "${KUBECONFIG}" get pods --no-headers --namespace "${NAMESPACE}"
+  NAMESPACE="${1:-$KUBESPACE}"
+  if [[ -n "$NAMESPACE" ]]; then
+    NAMESPACE_ARGS=( --namespace "${NAMESPACE}" )
+  else
+    NAMESPACE_ARGS=( --all-namespaces )
+  fi
+  kctl get pods --no-headers "${NAMESPACE_ARGS[@]}"
 }
 
 function kshell () {
-    local SERVICE="${1:-nginx-proxy}"
-    local NAMESPACE="${2:-$KUBESPACE}"
-    local SHELL="${3:-/bin/bash}"
-    local POD="$(kubectl --kubeconfig "${KUBECONFIG}" get pods --no-headers --namespace "${NAMESPACE}" | grep "^${SERVICE}" | awk '{print $1}' | sort | head -n 1)"
-    if [[ -n "${POD}" ]]; then
-        kubectl --kubeconfig "${KUBECONFIG}" exec --stdin --tty --namespace "${NAMESPACE}" "${POD}" -- "${SHELL}"
+  SERVICE="${1}"
+  if [[ -n "${SERVICE}" ]]; then
+    NAMESPACE="${2:-$KUBESPACE}"
+    if [[ -n "$NAMESPACE" ]]; then
+      NAMESPACE_ARGS=( --namespace "${NAMESPACE}" )
+      AWK_ARGS=( '{print $1}' )
     else
-        echo "Unable to identify pod for ${SERVICE} in ${NAMESPACE}" >&2
+      NAMESPACE_ARGS=( --all-namespaces )
+      AWK_ARGS=( '{print $2}' )
     fi
+    SHELL="${3:-/bin/bash}"
+    POD="$(kctl get pods --no-headers "${NAMESPACE_ARGS[@]}" | grep -P "\b${SERVICE}\b" | awk "${AWK_ARGS[@]}" | sort | head -n 1)"
+    if [[ -n "${POD}" ]]; then
+        kctl exec "${NAMESPACE_ARGS[@]}" --stdin --tty "${POD}" -- "${SHELL}"
+    else
+        echo "Unable to identify pod for ${SERVICE}" >&2
+    fi
+  else
+    echo "No service specified" >&2
+  fi
 }
 
 function klogs () {
-    local SERVICE="${1:-nginx-proxy}"
-    local NAMESPACE="${2:-$KUBESPACE}"
-    local SHELL="${3:-/bin/bash}"
-    local POD="$(kubectl --kubeconfig "${KUBECONFIG}" get pods --no-headers --namespace "${NAMESPACE}" | grep "^${SERVICE}" | awk '{print $1}' | sort | head -n 1)"
+  SERVICE="${1}"
+  if [[ -n "${SERVICE}" ]]; then
+    NAMESPACE="${2:-$KUBESPACE}"
+    if [[ -n "$NAMESPACE" ]]; then
+      NAMESPACE_ARGS=( --namespace "${NAMESPACE}" )
+      AWK_ARGS=( '{print $1}' )
+    else
+      NAMESPACE_ARGS=( --all-namespaces )
+      AWK_ARGS=( '{print $2}' )
+    fi
+    POD="$(kctl get pods --no-headers "${NAMESPACE_ARGS[@]}" | grep -P "\b${SERVICE}\b" | awk "${AWK_ARGS[@]}" | sort | head -n 1)"
     if [[ -n "${POD}" ]]; then
         if command -v stern >/dev/null 2>&1; then
-            stern --kubeconfig "${KUBECONFIG}" --namespace "${NAMESPACE}" --container '.*' --container-state all "${POD}"
+            kstern "${NAMESPACE_ARGS[@]}" --container '.*' --container-state all "${POD}"
         else
-            kubectl --kubeconfig "${KUBECONFIG}" logs --namespace "${NAMESPACE}" --follow=true --all-containers "${POD}"
+            kctl logs --follow=true --all-containers "${POD}"
         fi
     else
-        echo "Unable to identify pod for ${SERVICE} in ${NAMESPACE}" >&2
+        echo "Unable to identify pod for ${SERVICE}" >&2
     fi
+  else
+    echo "No service specified" >&2
+  fi
+}
+
+function kresources () {
+    NAMESPACE="${1:-$KUBESPACE}"
+    if [[ -n "$NAMESPACE" ]]; then
+      NAMESPACE_ARGS=( --namespace "${NAMESPACE}" )
+    else
+      NAMESPACE_ARGS=( --all-namespaces )
+    fi
+    for RESOURCE in $(kubectl api-resources --verbs=list --namespaced -o name); do
+      if [[ ! "$RESOURCE" =~ ^events.* ]]; then
+        echo "============================="
+        echo $RESOURCE
+        echo "-----------------------------"
+        kctl get --show-kind --ignore-not-found "${NAMESPACE_ARGS[@]}" "$RESOURCE"
+      fi
+    done
 }
